=== apache/flood/examples/flood.dtd
<?xml version="1.0" ?>

<!--

     This is a DTD for flood configuration files.
     With this file, validating XML software and
     heading line:

     <!DOCTYPE flood SYSTEM "flood.dtd">

     ...you can make sure your flood configuration
     is valid (in contrast to just "well-formed").

-->

<!ELEMENT flood (urllist+,profile+,farmer+,farm+,seed?)>

<!-- urllist -->
<!ELEMENT urllist (name,description?,baseurl?,(url|sequence)+)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT baseurl (#PCDATA)>

<!ELEMENT url (#PCDATA)>

<!ATTLIST url method (GET | POST | HEAD) #IMPLIED>
<!ATTLIST url payload CDATA #IMPLIED>
<!ATTLIST url payloadparam CDATA #IMPLIED>
<!ATTLIST url payloadparamcount CDATA #IMPLIED>
<!ATTLIST url payloadtemplate CDATA #IMPLIED>
<!ATTLIST url responsename CDATA #IMPLIED>
<!ATTLIST url responsetemplate CDATA #IMPLIED>
<!ATTLIST url requesttemplate CDATA #IMPLIED>
<!ATTLIST url requestparamcount CDATA #IMPLIED>
<!ATTLIST url predelay CDATA #IMPLIED>
<!ATTLIST url predelayprecision CDATA #IMPLIED>
<!ATTLIST url postdelay CDATA #IMPLIED>
<!ATTLIST url postdelayprecision CDATA #IMPLIED>
<!ATTLIST url user CDATA #IMPLIED>
<!ATTLIST url password CDATA #IMPLIED>
<!ATTLIST url Content-Type CDATA #IMPLIED>

<!ELEMENT sequence (url+)>

<!ATTLIST sequence sequencename CDATA #REQUIRED>
<!ATTLIST sequence sequencelist CDATA #REQUIRED>

<!-- profile -->

<!ENTITY % profile.events "(profile_init?,get_next_url?,create_req?,postprocess?,loop_condition?,profile_destroy?)+">
<!ENTITY % socket.events "(socket_init?,begin_conn?,send_req?,recv_resp?,end_conn?,request_destroy?,response_destroy?,socket_destroy?)+">
<!ENTITY % report.events "(report_init?,process_stats?,report_stats?,destroy_report?)+">

<!-- FIXME: this declaration doesn't exactly cover the flexibility of profile -->

<!ELEMENT profile (name,(description)?,useurllist,
                   (profiletype|%profile.events;),
                   (socket|%socket.events;),
                   verify_resp,
                   (report|%report.events;))>

<!ELEMENT useurllist (#PCDATA)>
<!ELEMENT profiletype (#PCDATA)>
<!ELEMENT socket (#PCDATA)>
<!ELEMENT verify_resp (#PCDATA)>
<!ELEMENT report (#PCDATA)>

<!ELEMENT profile_init (#PCDATA)>
<!ELEMENT get_next_url (#PCDATA)>
<!ELEMENT create_req (#PCDATA)>
<!ELEMENT postprocess (#PCDATA)>
<!ELEMENT loop_condition (#PCDATA)>
<!ELEMENT profile_destroy (#PCDATA)>

<!ELEMENT report_init (#PCDATA)>
<!ELEMENT process_stats (#PCDATA)>
<!ELEMENT report_stats (#PCDATA)>
<!ELEMENT destroy_report (#PCDATA)>

<!ELEMENT socket_init (#PCDATA)>
<!ELEMENT begin_conn (#PCDATA)>
<!ELEMENT send_req (#PCDATA)>
<!ELEMENT recv_resp (#PCDATA)>
<!ELEMENT end_conn (#PCDATA)>
<!ELEMENT request_destroy (#PCDATA)>
<!ELEMENT response_destroy (#PCDATA)>
<!ELEMENT socket_destroy (#PCDATA)>

<!-- farmer -->

<!ELEMENT farmer (name,description?,(count|time),useprofile+)>

<!ELEMENT count (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT useprofile (#PCDATA)>

<!-- farm -->

<!ELEMENT farm (name,description?,usefarmer+)>

<!ELEMENT usefarmer (#PCDATA)>

<!ATTLIST usefarmer count CDATA #IMPLIED>
<!ATTLIST usefarmer startcount CDATA #IMPLIED>
<!ATTLIST usefarmer startdelay CDATA #IMPLIED>

<!-- seed -->

<!ELEMENT seed (#PCDATA)>

=== apache/flood/examples/custom-content-type.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE flood SYSTEM "flood.dtd">
<flood configversion="1">
  <urllist>
    <name>Test Hosts</name>
    <description>A bunch of hosts we want to hit</description>

    <!-- Replace with your own domain (see RFC 2606, Section 3) -->
    <baseurl>http://www.example.com</baseurl>

    <!-- Simple multipart/form-data POST. Contains one plain variable 'foo' with
         value 'bar' and file variable 'logo', which refers to file 'asf_logo.gif'.
         Plese note, that this example has string 'XML encoded binary file
         contents' as file body, instead of actual data. This is intended, to make
         this example simple. In real scenario this string would have to be
         replaced by file contents encoded as XML entities. -->
    <url method="POST"
         Content-Type="multipart/form-data; boundary=AaB03x"
         payload="--AaB03x&#x0D;&#x0A;Content-Disposition: form-data; name=&quot;foo&quot;&#x0D;&#x0A;&#x0D;&#x0A;bar&#x0D;&#x0A;--AaB03x&#x0D;&#x0A;Content-Disposition: form-data; name=&quot;logo&quot;; filename=&quot;asf_logo.gif&quot;&#x0D;&#x0A;Content-Type: image/gif&#x0D;&#x0A;&#x0D;&#x0A;XML encoded binary file contents;&#x0D;&#x0A;--AaB03x--">/foo</url>

    <!-- Example XML-RCP query, as found in protocol spec. It calls method
         'examples.getStateName' with one integer argument. -->
    <url method="POST"
         Content-Type="text/xml"
         payload="&lt;xml version=&quot;1.0&quot;&gt;&lt;methodCall&gt;&lt;methodName&gt;examples.getStateName&lt;/methodName&gt;&lt;params&gt;&lt;param&gt;&lt;value&gt;&lt;i4&gt;41&lt;/i4&gt;&lt;/value&gt;&lt;/param&gt;&lt;/params&gt;&lt;/methodCall&gt;">/foo</url>
  </urllist>

  <profile>
    <name>RoundRobinProfile</name>
    <description>Round Robin Configuration</description>
    <useurllist>Test Hosts</useurllist>
    <profiletype>round_robin</profiletype>
    <socket>generic</socket>
    <verify_resp>verify_200</verify_resp>
    <report>relative_times</report>
  </profile>

  <farmer>
    <name>Joe</name>
    <useprofile>RoundRobinProfile</useprofile>
  </farmer>

  <farm>
    <name>Bingo</name>
    <usefarmer>Joe</usefarmer>
  </farm>

</flood>

=== apache/flood/examples/round-robin-keepalive.xml
<?xml version="1.0"?>
<!DOCTYPE flood SYSTEM "flood.dtd">
<!-- Hi, I'm a flood config file.  
     This is a keepalive-enabled profile.  -->
<flood configversion="1">
  <!-- A urllist describes which hosts and which methods we want to hit. -->
  <urllist>
    <name>Test Hosts</name>
    <description>A bunch of hosts we want to hit</description>
    <!-- Three static non-MultiView URLs that are included in Apache 2.0 -->
    <url>http://localhost:8080/index.html.en</url>
    <url>http://localhost:8080/manual/index.html.en</url>
    <url>http://localhost:8080/manual/mod/index-bytype.html</url>
  </urllist>

  <!-- The profile describes how we will hit the urllists. 
       Round robin runs all of the URLs in the urllist in order once. -->
  <profile>
    <name>RoundRobinProfile</name>
    <description>Round Robin Configuration</description>

    <useurllist>Test Hosts</useurllist>

    <!-- Profile Events -->
    <profile_init>round_robin_profile_init</profile_init>
    <create_req>round_robin_create_req</create_req>
    <get_next_url>round_robin_get_next_url</get_next_url>
    <loop_condition>round_robin_loop_condition</loop_condition>
    <profile_destroy>round_robin_profile_destroy</profile_destroy>

    <!-- Socket Events -->
    <socket_init>keepalive_socket_init</socket_init>
    <begin_conn>keepalive_begin_conn</begin_conn>
    <send_req>keepalive_send_req</send_req>
    <recv_resp>keepalive_recv_resp</recv_resp>
    <end_conn>keepalive_end_conn</end_conn>
    <socket_destroy>keepalive_socket_destroy</socket_destroy>

    <!-- Verification Events -->
    <verify_resp>verify_200</verify_resp>

    <!-- Reporting Events -->
    <report_init>easy_report_init</report_init>
    <process_stats>easy_process_stats</process_stats>
    <report_stats>easy_report_stats</report_stats>
    <destroy_report>easy_destroy_report</destroy_report>
  </profile>

  <!-- A farmer runs one profile a certain number of times.  -->
  <farmer>
    <name>Joe</name>
    <!-- run the Joe farmer 1000 times -->
    <count>1000</count>
    <!-- Joe uses this profile -->
    <useprofile>RoundRobinProfile</useprofile>
  </farmer>

  <!-- A farm contains a bunch of farmers - each farmer is a thread.  -->
  <farm>
    <name>Bingo</name>
    <!-- Create 10 identical Joe farmers executing in parallel. -->
    <usefarmer count="10">Joe</usefarmer>
  </farm>

  <!-- Set the seed to a known value so we can reproduce the same tests -->
  <seed>23</seed>
</flood>
